### ISSUE TITLE
请作者补充一下 README.md

### ISSUE THREAD

**Issue by angustar** [androidmumo/Bing-upyun#2]
在 README.md 的**4.1.1 准备工作**中，应该在`又拍云存储库`-`图片处理`-`创建缩略图版本`中创建`版本名称`分别为`bing25`和`bing1`的自定义图片处理服务，否则会导致缩略图生成失败。其中：
+ `bing1`的具体参数是：缩略方式选择`限定宽度，高度自适应`，限定尺寸为`16`px，图片质量为`100`%，其它不变。
+ `bing25`的具体参数是：缩略方式选择`限定宽度，高度自适应`，限定尺寸为`480`px，图片质量为`100`%，其它不变。

如图所示：

![Snipaste_2021-02-19_21-47-56.png](https://i.loli.net/2021/02/19/WMiEsdDVxbuZfq5.png)

README.md 里没有提到这一点，之前我一直只部署了后端 api，就没有发现缩略图有问题，今天搭建前端时才发现采集了半个多月的图片都没有缩略图……

**Comment by androidmumo** [comment]
您可以将对README.md的更改单独发个PR，我来合并

**Comment by angustar** [comment]
您好！我刚去试了一下，发现我这边之前fork过并且已经多次commit了，好像没有办法再fork一份。请问您了解其它方法嘛，或者您参照我的版本手动修改一下（见4.1.1）？
我fork后的项目地址：https://github.com/ikaleo/Bing-upyun/

**Comment by androidmumo** [comment]
> 您好！我刚去试了一下，发现我这边之前fork过并且已经多次commit了，好像没有办法再fork一份。请问您了解其它方法嘛，或者您参照我的版本手动修改一下（见4.1.1）？
> 我fork后的项目地址：https://github.com/ikaleo/Bing-upyun/

已经修改，感谢您的参与
